In [66]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [67]:
data=pd.read_csv('/home/mohamed/Desktop/fetchars.csv')

In [68]:
data.head()

age  duration  campaign  pdays  previous  emp.var.rate  \
0  1.200000  0.326262 -0.584963    0.0       0.0           0.0   
1  1.266667 -0.165723 -0.584963    0.0       0.0           0.0   
2 -0.066667  0.199766 -0.584963    0.0       0.0           0.0   
3  0.133333 -0.154038 -0.584963    0.0       0.0           0.0   
4  1.200000  0.468954 -0.584963    0.0       0.0           0.0   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  ...  month_0  \
0        0.266594       0.857143        0.0          0.0  ...        0   
1        0.266594       0.857143        0.0          0.0  ...        0   
2        0.266594       0.857143        0.0          0.0  ...        0   
3        0.266594       0.857143        0.0          0.0  ...        0   
4        0.266594       0.857143        0.0          0.0  ...        0   

   month_1  month_2  month_3  day_of_week_0  day_of_week_1  day_of_week_2  \
0        0        0        1              0              0              1   
1        0        0        1              0              0              1   
2        0        0        1              0              0              1   
3        0        0        1              0              0              1   
4        0        0        1              0              0              1   

   poutcome_0  poutcome_1  y  
0           0           1  0  
1           0           1  0  
2           0           1  0  
3           0           1  0  
4           0           1  0  

[5 rows x 39 columns]

In [69]:
data.shape

(41176, 39)

In [5]:
final_data=data[['age','campaign','pdays','previous','euribor3m','job_0',
       'job_1', 'job_2', 'job_3', 'marital_0', 'marital_1', 'marital_2',
       'education_0', 'education_1', 'education_2', 'education_3', 'default_0',
       'default_1', 'housing_0', 'housing_1', 'loan_0', 'loan_1', 'contact_0',
       'contact_1', 'month_0', 'month_1', 'month_2', 'month_3',
       'day_of_week_0', 'day_of_week_1', 'day_of_week_2', 'poutcome_0',
       'poutcome_1', 'y']]

NameError: name 'data' is not defined

In [71]:
final_data.head()

age  campaign  pdays  previous  euribor3m  job_0  job_1  job_2  job_3  \
0  1.200000 -0.584963    0.0       0.0        0.0      0      0      0      1   
1  1.266667 -0.584963    0.0       0.0        0.0      0      0      1      0   
2 -0.066667 -0.584963    0.0       0.0        0.0      0      0      1      0   
3  0.133333 -0.584963    0.0       0.0        0.0      0      0      1      1   
4  1.200000 -0.584963    0.0       0.0        0.0      0      0      1      0   

   marital_0  ...  month_0  month_1  month_2  month_3  day_of_week_0  \
0          0  ...        0        0        0        1              0   
1          0  ...        0        0        0        1              0   
2          0  ...        0        0        0        1              0   
3          0  ...        0        0        0        1              0   
4          0  ...        0        0        0        1              0   

   day_of_week_1  day_of_week_2  poutcome_0  poutcome_1  y  
0              0              1           0           1  0  
1              0              1           0           1  0  
2              0              1           0           1  0  
3              0              1           0           1  0  
4              0              1           0           1  0  

[5 rows x 34 columns]

In [4]:
X = final_data.drop(columns='y')
y = final_data['y']

NameError: name 'final_data' is not defined

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

NameError: name 'X' is not defined

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix ,classification_report

In [75]:
#معرفة اهم الاعمده
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X, y)

importances = pd.Series(rf.feature_importances_, index=X.columns)
importances.sort_values(ascending=False, inplace=True)
print(importances)


euribor3m        0.204329
age              0.192401
campaign         0.088533
pdays            0.059920
day_of_week_2    0.024402
education_3      0.023586
job_3            0.022970
job_1            0.022491
education_2      0.022477
day_of_week_1    0.021517
month_3          0.021515
education_1      0.021218
job_2            0.021044
housing_0        0.021015
housing_1        0.020626
day_of_week_0    0.020111
marital_1        0.018929
previous         0.018581
month_0          0.017840
month_2          0.016473
loan_0           0.014872
marital_2        0.014488
job_0            0.014143
loan_1           0.013684
poutcome_1       0.012576
month_1          0.012339
poutcome_0       0.010512
contact_1        0.007994
contact_0        0.007174
default_0        0.005794
default_1        0.005522
marital_0        0.000659
education_0      0.000268
dtype: float64


In [2]:

rf_model = RandomForestClassifier(
    n_estimators=200,  
    max_depth=10,       
    random_state=42
)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print('clasefcation report \n',classification_report(y_test, y_pred))

NameError: name 'X_train' is not defined

In [77]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

# فصل Features و Target
X = final_data.drop(columns='y')
y = final_data['y']

# تقسيم البيانات
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# إنشاء الموديل مع التعامل مع عدم توازن البيانات
rf_model_balanced = RandomForestClassifier(
    n_estimators=400,        # زيادة عدد الأشجار
    max_depth=14,             # عمق أكبر مع تجنب overfitting
    random_state=42,
    class_weight='balanced'   # يوازن بين y=0 و y=1

)


# تدريب الموديل
rf_model_balanced.fit(X_train, y_train)

# توقع وتقييم
y_pred = rf_model_balanced.predict(X_test)
y_proba = rf_model_balanced.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.8838028169014085
ROC-AUC: 0.7918203863739313
Confusion Matrix:
 [[6818  490]
 [ 467  461]]

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.93      0.93      7308
           1       0.48      0.50      0.49       928

    accuracy                           0.88      8236
   macro avg       0.71      0.71      0.71      8236
weighted avg       0.89      0.88      0.88      8236



In [78]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve
)

# ===============================
# 1️⃣ فصل Features و Target
# ===============================
X = final_data.drop(columns='y')
y = final_data['y']

# ===============================
# 2️⃣ تقسيم البيانات (مع stratify)
# ===============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ===============================
# 3️⃣ إنشاء وتدريب الموديل
# ===============================
rf_model = RandomForestClassifier(
    n_estimators=400,
    max_depth=14,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

# ===============================
# 4️⃣ التوقع بالاحتمالات
# ===============================
y_proba = rf_model.predict_proba(X_test)[:, 1]

# ===============================
# 5️⃣ التقييم الافتراضي (Threshold = 0.5)
# ===============================
y_pred_default = (y_proba >= 0.5).astype(int)

print("===== Threshold = 0.5 =====")
print("Accuracy:", accuracy_score(y_test, y_pred_default))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_default))
print("\nClassification Report:\n", classification_report(y_test, y_pred_default))

# ===============================
# 6️⃣ Threshold مخصص (بنكي)
# ===============================
custom_threshold = 0.30
y_pred_custom = (y_proba >= custom_threshold).astype(int)

print("\n===== Threshold = 0.30 =====")
print("Accuracy:", accuracy_score(y_test, y_pred_custom))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_custom))
print("\nClassification Report:\n", classification_report(y_test, y_pred_custom))

# ===============================
# 7️⃣ اختيار Threshold تلقائي (أقصى F1 للفئة 1)
# ===============================
thresholds = np.arange(0.1, 0.9, 0.05)
results = []

for t in thresholds:
    y_pred_t = (y_proba >= t).astype(int)
    report = classification_report(y_test, y_pred_t, output_dict=True)
    results.append({
        'threshold': t,
        'precision_1': report['1']['precision'],
        'recall_1': report['1']['recall'],
        'f1_1': report['1']['f1-score']
    })

threshold_df = pd.DataFrame(results).sort_values('f1_1', ascending=False)
print("\n===== Best Thresholds by F1 (Class 1) =====")
print(threshold_df.head())

# ===============================
# 8️⃣ Feature Importance (للتفسير)
# ===============================
feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print("\n===== Top 10 Important Features =====")
print(feature_importance.head(10))


===== Threshold = 0.5 =====
Accuracy: 0.8838028169014085
ROC-AUC: 0.7918203863739313
Confusion Matrix:
 [[6818  490]
 [ 467  461]]

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.93      0.93      7308
           1       0.48      0.50      0.49       928

    accuracy                           0.88      8236
   macro avg       0.71      0.71      0.71      8236
weighted avg       0.89      0.88      0.88      8236


===== Threshold = 0.30 =====
Accuracy: 0.7332442933462846
ROC-AUC: 0.7918203863739313
Confusion Matrix:
 [[5373 1935]
 [ 262  666]]

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.74      0.83      7308
           1       0.26      0.72      0.38       928

    accuracy                           0.73      8236
   macro avg       0.60      0.73      0.60      8236
weighted avg       0.87      0.73      0.78      8236


===== Best Thresholds by F1 (Cl